<a href="https://colab.research.google.com/github/hyelim-kim1028/NLP/blob/main/tensorflow2%26ml_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#텐서플로2와 머신러닝으로 시작하는 자연어처리 

출판사: 위키북스

#01. 들어가며

In [ ]:
# clone the git rep on colab <!git clone ~> 
!git clone https://github.com/hyelim-kim1028/tensorflow-ml-nlp-tf2.git

Cloning into 'tensorflow-ml-nlp-tf2'...
remote: Enumerating objects: 1715, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 1715 (delta 42), reused 9 (delta 5), pack-reused 1631
Receiving objects: 100% (1715/1715), 201.17 MiB | 22.29 MiB/s, done.
Resolving deltas: 100% (1032/1032), done.
Checking out files: 100% (88/88), done.


In [ ]:
# 필요 라이브버리 설치 <!pip install ~>  
#!pip install -r requirements.txt
!pip install tensorflow

In [ ]:
import tensorflow as tf

#02.자연어 처리 개발 준비

- 텐서플로 
- 사이킷런 
- 자연어 토크나이징 도구
- 그 밖의 라이브러리 (전처리) 

In [ ]:
# tf.keras.layers 
# y = f(Wx + b)

W = tf.Variable(tf.random.uniform([5,10], -1.0, 1.0))
b = tf.Variable(tf.zeros([10]))

y = tf.matmul(W, x) + b
# NameError: name 'x' is not defined 



NameError: ignored

In [ ]:
# Dense층 객체에 입력값 설정  
#1. Dense객체 생성 및 입력값 설정 
dense = tf.keras.layers.Dense(...)
output = dense(input)

#2. 객체 생성 시 입력값 설정 
output = tf.keras.layers.Dense(...)(input)


In [ ]:
#Dense 층에 가중치, 편향 초기화 방법, 활성화 함수의 종류 옵션 설정 

__init__(
    units,
    activation = None, # 활성화 함수 
    use_bias = True,  #가중치 
    kernel_initializer = 'glorot_uniform',# 가중치 초기화 
    bias_initializer = 'zeros', # 편향 초기화 
    kernel_regularizer = None, 
    bias_regularizer = None,
    activity_regularizer = None, 
    kernel_constraint = None, 
    bias_constraint = None, 
    **kwargs 
)

In [ ]:
# 신경망 생성 
INPUT_SIZE = (20, 1)

inputs = tf.keras.layers.Input(shape = INPUT_SIZE)
hidden = tf.keras.layers.Dense(units=10, activation = tf.nn.sigmoid)(inputs) #10의 노드 은닉층 
output  = tf.keras.layers.Dense(units = 2, activation = tf.nn.sigmoid)(hidden) #2개의 출력 노드 

In [ ]:
# tf.keras.layers.Dropout

# 1. 객체 생성 후 다시 호출하면서 입력값 설정 
dropout = tf.keras.layers.Dropout(...)
output = dropout(input)

# 2. 객체 생성 시 입력값 설정 
output = tf.keras.layers.Dropout(...)(input)

__init__(
    rate, 
    noise_shape = None, 
    seed = None, 
    **kwargs 
)

In [ ]:
INPUT_SIZE = (20, 1)

inputs = tf.keras.layers.Input(shape = INPUT_SIZE)
dropout = tf.keras.layers.Dropout(rate = 0.5)(inputs)

# tf.keras.layers.dropout 
# 0.2 > 20%노드를 0으로 만든다 
# tf.nn.dropout 
# 0.2 > 80%의 노드를 0으로 만든다 

In [ ]:
#dense층 신경망 구조에 드롭아웃 적용 

inputs = tf.keras.layers.Input(shape = INPUT_SIZE)
dropout = tf.keras.layers.Dropout(rate=0.2)(input)
hidden = tf.keras.layers.Dense(units = 10, activation = tf.nn.sigmoid)(dropout)
output = tf.keras.layers.Dense(units = 2, activation = tf.nn.sigmoid )(hidden)


In [ ]:
# 1. 객체 생성 후 다시 호출하면서 입력값 설정 
conv1d = tf.keras.layers.Conv1D(...)
output = conv1d(input)

# 2. 객체 생성 시 입력값 설정 
output = tf.keras.layers.Conv1D(...)(input)

# 객체 생성 시 전달 인자 
__init__(
    filters, # 몇개의 필터 사용 
    #conv1D는 필터의 가로 길이만 설정 #세로는 1D는 상관 없음 
    kernel_size, #필터의 가로 길이 
    strides = 1,
    padding = 'valid',
    data_format = 'channels_last',
    dilation_rate = 1,
    activation = None, 
    use_bias = True, 
    kernel_initializer = 'glorot_uniform',
    bias_initializer = 'zeros',
    kernel_regularizer = None, 
    bias_regularizer = None, 
    activity_regularizer = None, 
    kernel_constraint = None, 
    bias_constraint = None, 
    **kwargs 
)

In [ ]:
# conv1D를 사용한 합성곱 신경망 

INPUT_SIZE = (1,28,28)

inputs = tf.keras.Input(shape = INPUT_SIZE)
conv = tf.keras.layers.Conv1D(
    filters = 10,
    kernel_size = 3,
    padding = 'same',
    activation = tf.nn.relu
)(inputs)

In [ ]:
# dropout 적용 

INPUT_SIZE = (1, 28, 28)

inputs = tf.keras.Input(shape = INPUT_SIZE)
dropout = tf.keras.layers.Dropout(rate = 0.2)(inputs)
conv = tf.keras.layers.Conv1D(filters = 10, kernel_size = 3, padding = 'same', activation = tf.nn.relu)(dropout)

In [ ]:
# tf.keras.layers.MaxPool1D 
# feature map의 크기를 줄이거나 주요한 특징을 뽑아내기 위해 합성곱 이후에 적용 
# max pooling: 최댓값만 뽑아냄 #average pooling: 평균값만 뽑아냄 

# MaxPool1D, MaxPool2D, MaxPool3D 

# 1. 객체 생성 후 apply 함수를 이용해 입력값 설정 
max_pool = tf.keras.layers.MaxPool1D(...)
max_pool.apply(input)

# 2. 객체 생성 시 입력값 설정 
max_pool = tf.keras.layers.MaxPool1D(...)(input)

__init__(
    pool_size = 2, #필터의 크기 
    strides = None, # 적용할 스트라이드 값 
    padding = 'valid', # same or valid 
    data_format = None, #channel_last = (batch, length, channels) #channel_first = (batch, channels, length) 
    **kwargs
)

In [ ]:
# maxpooling, dropout 적용 

INPUT_SIZE = (1, 28, 28)

inputs = tf.keras.Input(shape = INPUT_SIZE)
dropout = tf.keras.layers.Dropout(rate = 0.2)(input)
conv = tf.keras.layers.Conv1D(
    filters = 10,
    kernel_size = 3,
    padding = 'same',
    activation = tf.nn.relu
)(input)
max_pool = tf.keras.layers.MaxPool1D(pool_size = 3, padding = 'same')(conv)
flatten = tf.keras.layers.Flatten()(max_pool)
hidden = tf.keras.layers.Dense(units=50, activation = tf.nn.relu)(flatten)
output = tf.keras.layers.Dense(units = 10, activation = tf.nn.softmax)(hidden)

- API clean up 
- Eager Execution 
- No more globals 
- Functions, not sessions 

#- model construction (Keras API) 
#  - Sequential API 
#  - Functional API 
#  - Functional/Sequential API 
#    +) Custom Layers 
#  - Subclassing (Custom Model) 


In [ ]:
# keras #Sequentail API # simpy Fully-connected layer 

from tensorflow.keras import layers 

model = tf.keras.Sequential()
model.add(layers.Dense(64, activation = 'relu'))
model.add(layers.Dense(64, activation = 'relu'))
model.add(layers.Dense(10, activation = 'softmax'))

# sequential 
# stack 형에는 접합하지만, 복잡한 구조에는 어려움 
# 다중 입력값 모델 (Multi-input models)
# 다중 출력값 모델 (Multi-output models)
# 공유 층을 활용하는 모델 (Models with shared layers)
# 데이터 흐름이 순차적이지 않은 모델 (Models with non-sequential data flows)
# Functional API or subclassing 방식 사용 

In [ ]:
# Functional API 
inputs = tf.keras.Input(shape=(32,)) # = tf.placeholder0
x = layers.Dense(64, activation = 'relu')(inputs)
x = layers.Dense(64, activation = 'relu')(x)
predictions = layers.Dense(10, activation = 'softmax')(x)

In [ ]:
class CustomLayer(layers.layer):

  def __init__(self, hidden_dimension, hidden_dimension2, output_dimension):
    self.hidden_dimension = hidden_dimension 
    self.hidden_dimension2 = hidden_dimension2 
    self.output_dimension = output_dimension 
    super(CustomLayer, self).__init__()

  def build(self, input_shape): # 모델 가중치 
    self.dense_layer1 = layers.Dense(self.hidden_dimension, activation = 'relu')
    self.dense_layer2 = layers.Dense(self.hidden_dimension2, activation = 'relu')
    self.dense_layer3 = layers.Dense(self.output_dimenstion, activation = 'softmax')

  def call(self, inputs): # 층의 로직 정의 
    x = self.dense_layer1(inputs)
    x = self.dense_layer2(x)

    return self.dense_layer3(x)
    

In [ ]:
#sequential 모듈 활용 
from tensorflow.keras import layers 

model = tf.keras.Sequential()
model.add(CustomLayer(64, 64, 10))


In [ ]:
# Subclassing (Custom Model)

class MyModel(tf.keras.Model):

  def __init__(self, hidden_dimension, hidden_dimension2, output_dimension):
    # 모델에 사용될 층과 변수 정의 
    super(MyModel, self).__init__(name = 'my model')
    self.dense_layer1 = layers.Dense(hidden_dimension, activation = 'relu')
    self.dense_layer2 = layers.Dense(hidden_dimension2, activation = 'relu')
    self.dense_layer3 = layers.Dense(output_dimension, activation = 'softmax')
  
  def call(self, inputs):
    # 모델 연산 진행 
    x = self.dense_layer1(inputs)
    x = self.dense_layer2(x)

    return self.dense_layer3(x)


#모델 학습 

1) keras 내장 API 활용 
(i.e. model.fit(), model.evaluate(), model.predict())

2) 학습, 검증, 예측 등 모든 과정을 GradientTape 객체를 활용해 직접 구현하는 방법 


In [ ]:
# 내장 API를 활용하는 방법 

# 1. 학습 과정 정의 
# 손실 함수 (loss function), 옵티마이저 (optimizer), 평가 지표 (metric)

#객체 형식 지정 
model.compie(optimizer = tf.keras.optimizers.Adam(),
             loss = tf.keras.losses.CategoricalCrossentropy(),
             metrics = [tf.keras.metrics.Accuracy()])

#문자열 형태 지정 
model.compile(optimizer = 'adam', 
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])



In [ ]:
model.fit(x_train, y_train, 
          batch_size = 64, 
          epochs = 3, 
          validation_data = (x_val, y_val))
          # epoch 마다 검증 결과를 보기 위해서는 
          # fit 함수의 검증 데이터를 추가로 넣으면 된다 



In [ ]:
# 더미 데이터를 활용한 감정 분석 모델링 

# 입력값: 단어 > 임베딩 벡터 
# 백터 평균 > 하나의 백터 
# 결과값: 시그모이드, 0~1 

# 모델 구현 

import tensorflow as tf 
from tensorflow.keras import preprocessing

samples = ['너 오늘 이뻐 보인다',
           '나는 오늘 기분이 더러워',
           '끝내주는데, 좋은 일이 있나봐',
           '나 좋은 일이 생겼어',
           '아 오늘 진짜 짜증나',
           '환상적인데, 정말 좋은거 같아']

labels = [[1],[0],[1],[1],[0],[1]]
tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)

word_index = tokenizer.word_index

In [ ]:
# 모델 구축 및 모델 학습에 필요한 변수 정의 

batch_size = 2
num_epochs = 100 
vocab_size = len(word_index) + 1
# 모델 하이퍼 파라미터 (임베딩 층, 은닉층, 출력층)
emb_size = 128 
hidden_dimension= 256 
output_dimension = 1 

In [ ]:
# Sequential API 를 활용한 심층 신경망 모델 

#방법 1 # Sequential 객체 생성 후 각 층 추가 
model = tf.keras.Sequential() 
model.add(layers.Embedding(vocab_size, emb_size, input_length = 4))
model.add(layers.Lambda(lambda x: tf.reduce_mean(x, axis = 1)))
model.add(layers.Dense(hidden_dimension, activation = 'relu'))
model.add(layers.Dense(output_dimension, activation = 'sigmoid'))

# 방법 2 # 객체 생성 시 인자로 사용할 층을 순차적으로 리스트로 만들어서 전달 
model = tf.keras.Sequential([
layers.Embedding(vocab_size, emb_size, input_length = 4),
layers.Lambda(lambda x: tf.reduce_mean(x, axis = 1)),
layers.Dense(hidden_dimension, activation = 'relu'),
layers.Dense(output_dimension, activation = 'sigmoid')                             
])

# 입력값 embdding 층 추가 
# 임베딩 된 단어의 백터 평균 > lambda층 사용 
# 0~1 사이 > sigmoid 사용 

#모델 컴파일 메서드 # 학습 과정 정의 
# 옵티마이저 > Adam 최적화 
# 이진분류 > binary cross-entropy 
# 모델 측정 지표 > accuracy 

model.compile(optimizer =  tf.keras.optimizers.Adam(0.001),
              loss = 'binary_crossentropy',
              metrics = ['accuracy']) 

# fit 메서드 # 학습 진행 
model.fit(input_sequences, lables, epochs = num_epochs, batch_size = batch_size)

In [ ]:
# Functional API으로 동일 구현 

inputs = layers.Input(shape = (4,))
embed_output = layers.Embedding(vocab_size, emb_size)(inputs)
pooled_output = tf.reduce_mean(embed_output, axis = 1)
hidden_layer = layers.Dense(hidden_dimension, activation = 'relu')(pooled_output)
outputs = layers.Dense(output_dimension, activation = 'sigmoid')(hidden_layer)
model = tf.keras.model(inputs = inputs, outputs = outputs)

model.compile(optimizer = tf.keras.optimizers.Adam(0.001),
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.fit(input_sequences, labels, epochs = num_epochs, batch_size = batch_size)

In [ ]:
# Subclassing으로 모델 구현 

class CustomModel(tf.keras.Model):

  def __init__(self, vocab_size, embed_dimension, hidden_dimension, output_dimension):
    super(CustomModel, self).__init__(name = 'my_model')
    self.embedding = layers.Embedding(vocab_size,embed_dimension)
    self.dense_layer = layers.Dense(hidden_dimension, activation = 'relu')
    self.output_layer = layers.Dense(output_dimension, activation = 'sigmoid')

  def call(self, inputs):
    x =self.embedding(inputs)
    x = tf.reduce_mean(x, axis = 1)
    x = self.dense_layer(x)
    x = self.output_layer(x)

    return x 

model = CustomModel(vocab_size = vocab_size, 
                    embed_dimension = embed_size,
                    hidden_dimension = hidden_dimension, 
                    output_dimension = output_dimension)

model.compile(optimizer = tf.keras.optimizers.Adam(0.001),
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(input_sequences, labels, epochs = num_epochs, batch_size = batch_size)



tensorflow 공식 API 문서

www.tensorflow.org/api_docs/python/tf

#Scikit-learn 

- 머신러닝을 위한 파이썬 라이브러리 
<> 딥러닝: tensorflow, keras, pytorch 

- 지도학습 모듈
    - Naive Bayes 
    - Decision Trees 
    - Support Vector Machines 
- 비지도학습 모듈
    - Clustering (군집화) 
    - Gaussian mixture models 
- 모델 선택 및 평가를 위한 모듈
    - 모델 교차 검증 (Cross validation) 
    - 모델 평가 (Model evaluation) 
- 데이터 변환 및 데이터 불러오기 모듈
    - pipeline 
    - feature extraction
    - preprocessing data
    - dimensionality reduction 
- 계산 성능 향상 모듈 


In [1]:
# scikit-learn 설치 
!pip install scikit-learn

In [2]:
import sklearn 
sklearn.__version__

'0.22.2.post1'

In [5]:
# 하나의 데이터 #iris # 두가지 분류모델 
# 1. 지도학습모델 (K-nearest neighbor classifier)
# 2. 비지도학습모델 (k-means clustering)

from sklearn.datasets import load_iris # iris 내장 데이터 불러오기 

# 변수 할당 # 데이터 구성 출력 
iris_dataset = load_iris()
print("iris_dataset key: {}".format(iris_dataset.keys()))

print(iris_dataset['data'])
print("shape of data: {}".format(iris_dataset['data'].shape))

iris_dataset key: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6

In [8]:
print(iris_dataset['feature_names'])
print(iris_dataset['target'])
print(iris_dataset['target_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [9]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

#Scikit-learn을 활용한 데이터 분리 

- 학습 데이터 > 학습 데이터 & 평가 데이터 


In [12]:
from sklearn.model_selection import train_test_split

train_input,test_input, train_label, test_label = train_test_split(iris_dataset['data'], iris_dataset['target'],test_size = 0.25, random_state = 42)
# test_size = 0~1 

print("shape of train_input: {}".format(train_input.shape)) #112, 4
print("shape of test_input:{}".format(test_input.shape)) #38, 4
print("shape of train_label: {}".format(train_label.shape)) #112, 
print("shape of test_label: {}".format(test_label.shape))#38, 

# 학습데이터, 평가 데이터, 검증 데이터 
# 학습 데이터: 모델 학습 > 검증 데이터: 모델 검증 및 하이퍼파라미터 수정 > 평가 데이터  

shape of train_input: (112, 4)
shape of test_input:(38, 4)
shape of train_label: (112,)
shape of test_label: (38,)


In [14]:
# Scikit-learn 지도학습 
# K-nearest neighbor classifier 
# k: 예측하고자 하는 데이터와 가까운 몇개의 데이터를 참고할 것인가 

from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 1)

knn.fit(train_input, train_label) #모델에 학습데이터 & 라벨값 적용 

KNeighborsClassifier(algorithm = 'auto', leaf_size = 30, metric = 'minkowski',
                     metric_params = None, n_jobs = 1,n_neighbors = 1, p = 2, 
                     weights = 'uniform')

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=1, n_neighbors=1, p=2,
                     weights='uniform')

In [21]:
# 새로운 데이터 라벨 예측 

#임의의 피쳐값 설정 
import numpy as np 
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])
knn.predict(new_input) # 1 = Versicolor 로 예측 

array([1])

In [22]:
# 평가 데이터로 예측 
predict_label = knn.predict(test_input)
print(predict_label)

print(acc)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


#03. 자연어 처리 개요 
- 단어표현 
- 텍스트 분류
- 텍스트 유사도 
- 자연어 생성 
- 기계 이해 
- 데이터 이해하기 


#04.텍스트 분류

- 영어 텍스트 분류 
- 한글 텍스트 분류

#05.텍스트 유사도
- 문제 소개 
- 데이터 분석과 전처리 
- 모델링 
- 정리 

#06.챗봇 만들기
- 데이터 소개 
- 데이터 분석
- 시퀀스 투 시퀀스 모델 
- 트랜스포머 모델 
- 정리 

#07.사전 학습 모델 
- 버트 
- 버트를 활용한 미세 조정 학습 
- GPT 
- GPT2를 활용한 미세 조정 학습 
- 정리 